/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetointegrador;

/**
 *
 * @author pedrogomes
 */
public class CadastroClienteInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form MovimentacoesInternalFrame
     */
    public CadastroClienteInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        LabelMovimentacoes = new javax.swing.JLabel();
        PanelAjudaPesquisa = new javax.swing.JPanel();
        MenuAjuda = new javax.swing.JButton();
        TxtFildePesquisar = new javax.swing.JTextField();
        MenuPesquisar = new javax.swing.JButton();
        LabelAdicionarExcluir = new javax.swing.JPanel();
        MenuExcluir = new javax.swing.JButton();
        MenuAdicionar = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setToolTipText("");

        LabelMovimentacoes.setBackground(new java.awt.Color(228, 228, 228));
        LabelMovimentacoes.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        LabelMovimentacoes.setForeground(java.awt.Color.black);
        LabelMovimentacoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelMovimentacoes.setText("Cadastro Cliente");
        LabelMovimentacoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LabelMovimentacoes.setOpaque(true);

        PanelAjudaPesquisa.setBackground(new java.awt.Color(228, 228, 228));
        PanelAjudaPesquisa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        MenuAjuda.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        MenuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/ajuda.png"))); // NOI18N
        MenuAjuda.setText("Ajuda");

        TxtFildePesquisar.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        TxtFildePesquisar.setText("Ex. Rosa vermelha");
        TxtFildePesquisar.setMinimumSize(new java.awt.Dimension(23, 24));
        TxtFildePesquisar.setOpaque(false);
        TxtFildePesquisar.setPreferredSize(new java.awt.Dimension(100, 24));
        TxtFildePesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFildePesquisarActionPerformed(evt);
            }
        });

        MenuPesquisar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        MenuPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/pesquisa.png"))); // NOI18N
        MenuPesquisar.setText("Pesquisar");
        MenuPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAjudaPesquisaLayout = new javax.swing.GroupLayout(PanelAjudaPesquisa);
        PanelAjudaPesquisa.setLayout(PanelAjudaPesquisaLayout);
        PanelAjudaPesquisaLayout.setHorizontalGroup(
            PanelAjudaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAjudaPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuAjuda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(TxtFildePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MenuPesquisar)
                .addContainerGap())
        );
        PanelAjudaPesquisaLayout.setVerticalGroup(
            PanelAjudaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAjudaPesquisaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelAjudaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MenuAjuda)
                    .addComponent(TxtFildePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MenuPesquisar))
                .addContainerGap())
        );

        LabelAdicionarExcluir.setBackground(new java.awt.Color(228, 228, 228));
        LabelAdicionarExcluir.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        MenuExcluir.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        MenuExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/excluirCesta.png"))); // NOI18N
        MenuExcluir.setText("Excluir");
        MenuExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExcluirActionPerformed(evt);
            }
        });

        MenuAdicionar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        MenuAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/adicionarCesta.png"))); // NOI18N
        MenuAdicionar.setText("Adicionar");
        MenuAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LabelAdicionarExcluirLayout = new javax.swing.GroupLayout(LabelAdicionarExcluir);
        LabelAdicionarExcluir.setLayout(LabelAdicionarExcluirLayout);
        LabelAdicionarExcluirLayout.setHorizontalGroup(
            LabelAdicionarExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabelAdicionarExcluirLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(MenuAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LabelAdicionarExcluirLayout.setVerticalGroup(
            LabelAdicionarExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LabelAdicionarExcluirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LabelAdicionarExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MenuExcluir)
                    .addComponent(MenuAdicionar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelMovimentacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelAjudaPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelAdicionarExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelMovimentacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelAjudaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelAdicionarExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBounds(0, 0, 776, 487);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuAdicionarActionPerformed

    private void MenuExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuExcluirActionPerformed

    private void MenuPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuPesquisarActionPerformed

    private void TxtFildePesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFildePesquisarActionPerformed
        // TODO add your handling code here:

        String a = evt.toString();
        System.out.println(a);
    }//GEN-LAST:event_TxtFildePesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LabelAdicionarExcluir;
    private javax.swing.JLabel LabelMovimentacoes;
    private javax.swing.JButton MenuAdicionar;
    private javax.swing.JButton MenuAjuda;
    private javax.swing.JButton MenuExcluir;
    private javax.swing.JButton MenuPesquisar;
    private javax.swing.JPanel PanelAjudaPesquisa;
    private javax.swing.JTextField TxtFildePesquisar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
