/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetointegrador;

/**
 *
 * @author pedrogomes
 */
public class Movimentacoes extends javax.swing.JFrame {

    /**
     * Creates new form Movimentacoes
     */
    public Movimentacoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        LabelMovimentacoes = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        LabelDesconto = new javax.swing.JLabel();
        LabelNomeCliente = new javax.swing.JLabel();
        LabelValorTotal = new javax.swing.JLabel();
        PanelAjudaPesquisa = new javax.swing.JPanel();
        MenuAjuda = new javax.swing.JButton();
        TxtFildePesquisar = new javax.swing.JTextField();
        MenuPesquisar = new javax.swing.JButton();
        LabelAdicionarExcluir = new javax.swing.JPanel();
        MenuExcluir = new javax.swing.JButton();
        MenuAdicionar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaMovimentacoes = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        BarraMenus = new javax.swing.JMenuBar();
        MenuMovimentacoes = new javax.swing.JMenu();
        MenuProduto = new javax.swing.JMenu();
        SubMenuCadastroProduto = new javax.swing.JMenuItem();
        SubMenuConsutaCliente = new javax.swing.JMenuItem();
        SubMenuCadastroCliente = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        SubMenuConsultaCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 600));
        setResizable(false);

        LabelMovimentacoes.setBackground(new java.awt.Color(228, 228, 228));
        LabelMovimentacoes.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        LabelMovimentacoes.setForeground(java.awt.Color.black);
        LabelMovimentacoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelMovimentacoes.setText("Movimentações");
        LabelMovimentacoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LabelMovimentacoes.setOpaque(true);

        jPanel3.setBackground(new java.awt.Color(228, 228, 228));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelDesconto.setBackground(new java.awt.Color(193, 200, 247));
        LabelDesconto.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        LabelDesconto.setForeground(new java.awt.Color(51, 46, 155));
        LabelDesconto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDesconto.setText("Desconto R$ 50,00");
        LabelDesconto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LabelDesconto.setOpaque(true);

        LabelNomeCliente.setBackground(new java.awt.Color(193, 200, 247));
        LabelNomeCliente.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        LabelNomeCliente.setForeground(new java.awt.Color(51, 46, 155));
        LabelNomeCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNomeCliente.setText("Pedro Gomes");
        LabelNomeCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LabelNomeCliente.setOpaque(true);

        LabelValorTotal.setBackground(new java.awt.Color(193, 200, 247));
        LabelValorTotal.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        LabelValorTotal.setForeground(new java.awt.Color(51, 46, 155));
        LabelValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelValorTotal.setText("Valor Total R$ 500,00");
        LabelValorTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LabelValorTotal.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanelAjudaPesquisa.setBackground(new java.awt.Color(228, 228, 228));
        PanelAjudaPesquisa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        MenuAjuda.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        MenuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/ajuda.png"))); // NOI18N
        MenuAjuda.setText("Ajuda");

        TxtFildePesquisar.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        TxtFildePesquisar.setText("Ex. Rosa vermelha");
        TxtFildePesquisar.setMinimumSize(new java.awt.Dimension(23, 24));
        TxtFildePesquisar.setOpaque(false);
        TxtFildePesquisar.setPreferredSize(new java.awt.Dimension(100, 24));
        TxtFildePesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFildePesquisarActionPerformed(evt);
            }
        });

        MenuPesquisar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        MenuPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/pesquisa.png"))); // NOI18N
        MenuPesquisar.setText("Pesquisar");
        MenuPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAjudaPesquisaLayout = new javax.swing.GroupLayout(PanelAjudaPesquisa);
        PanelAjudaPesquisa.setLayout(PanelAjudaPesquisaLayout);
        PanelAjudaPesquisaLayout.setHorizontalGroup(
            PanelAjudaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAjudaPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuAjuda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TxtFildePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MenuPesquisar)
                .addContainerGap())
        );
        PanelAjudaPesquisaLayout.setVerticalGroup(
            PanelAjudaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAjudaPesquisaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelAjudaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MenuAjuda)
                    .addComponent(TxtFildePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MenuPesquisar))
                .addContainerGap())
        );

        LabelAdicionarExcluir.setBackground(new java.awt.Color(228, 228, 228));
        LabelAdicionarExcluir.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        MenuExcluir.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        MenuExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/excluirCesta.png"))); // NOI18N
        MenuExcluir.setText("Excluir");
        MenuExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExcluirActionPerformed(evt);
            }
        });

        MenuAdicionar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        MenuAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/adicionarCesta.png"))); // NOI18N
        MenuAdicionar.setText("Adicionar");
        MenuAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LabelAdicionarExcluirLayout = new javax.swing.GroupLayout(LabelAdicionarExcluir);
        LabelAdicionarExcluir.setLayout(LabelAdicionarExcluirLayout);
        LabelAdicionarExcluirLayout.setHorizontalGroup(
            LabelAdicionarExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabelAdicionarExcluirLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(MenuAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuExcluir)
                .addContainerGap(627, Short.MAX_VALUE))
        );
        LabelAdicionarExcluirLayout.setVerticalGroup(
            LabelAdicionarExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LabelAdicionarExcluirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LabelAdicionarExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MenuExcluir)
                    .addComponent(MenuAdicionar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelMovimentacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelAjudaPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelAdicionarExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelMovimentacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelAjudaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelAdicionarExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TabelaMovimentacoes.setAutoCreateRowSorter(true);
        TabelaMovimentacoes.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        TabelaMovimentacoes.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        TabelaMovimentacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Pranta",  new Float(500.0),  new Float(50.0),  new Integer(1),  new Float(450.0)},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Produto", "Valor Unitário", "Desconto", "Quantidade", "Sub total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TabelaMovimentacoes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TabelaMovimentacoes.setMaximumSize(new java.awt.Dimension(700, 54));
        TabelaMovimentacoes.setMinimumSize(new java.awt.Dimension(700, 54));
        TabelaMovimentacoes.setPreferredSize(new java.awt.Dimension(700, 54));
        TabelaMovimentacoes.setShowGrid(true);
        TabelaMovimentacoes.setSurrendersFocusOnKeystroke(true);
        TabelaMovimentacoes.getTableHeader().setResizingAllowed(false);
        TabelaMovimentacoes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TabelaMovimentacoes);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 819, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        BarraMenus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BarraMenus.setForeground(java.awt.Color.black);
        BarraMenus.setToolTipText("");
        BarraMenus.setDoubleBuffered(true);
        BarraMenus.setFocusable(false);
        BarraMenus.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        BarraMenus.setPreferredSize(new java.awt.Dimension(265, 30));
        BarraMenus.setVerifyInputWhenFocusTarget(false);

        MenuMovimentacoes.setBackground(java.awt.Color.black);
        MenuMovimentacoes.setForeground(java.awt.Color.black);
        MenuMovimentacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/cesta-de-compras-24.png"))); // NOI18N
        MenuMovimentacoes.setText("Movimentações");
        MenuMovimentacoes.setFont(MenuMovimentacoes.getFont().deriveFont(MenuMovimentacoes.getFont().getStyle() | java.awt.Font.BOLD));
        BarraMenus.add(MenuMovimentacoes);

        MenuProduto.setForeground(java.awt.Color.black);
        MenuProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/procurar-estoque-24.png"))); // NOI18N
        MenuProduto.setText("Produto");
        MenuProduto.setFont(MenuProduto.getFont().deriveFont(MenuProduto.getFont().getStyle() | java.awt.Font.BOLD));

        SubMenuCadastroProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/adicionar24.png"))); // NOI18N
        SubMenuCadastroProduto.setText("Cadastro");
        MenuProduto.add(SubMenuCadastroProduto);

        SubMenuConsutaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/pesquisa.png"))); // NOI18N
        SubMenuConsutaCliente.setText("Consulta");
        MenuProduto.add(SubMenuConsutaCliente);

        BarraMenus.add(MenuProduto);

        SubMenuCadastroCliente.setForeground(java.awt.Color.black);
        SubMenuCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/adicionar-usuário-masculino-24.png"))); // NOI18N
        SubMenuCadastroCliente.setText("Cliente");
        SubMenuCadastroCliente.setFont(SubMenuCadastroCliente.getFont().deriveFont(SubMenuCadastroCliente.getFont().getStyle() | java.awt.Font.BOLD));

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/adicionar-usuário-masculino-24.png"))); // NOI18N
        jMenuItem6.setText("Cadastro");
        SubMenuCadastroCliente.add(jMenuItem6);

        SubMenuConsultaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/procurar-usuário-masculino-24.png"))); // NOI18N
        SubMenuConsultaCliente.setText("Consulta");
        SubMenuCadastroCliente.add(SubMenuConsultaCliente);

        BarraMenus.add(SubMenuCadastroCliente);

        setJMenuBar(BarraMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(36, 36, 36)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(254, 254, 254)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(280, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtFildePesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFildePesquisarActionPerformed
        // TODO add your handling code here:

        String a = evt.toString();
        System.out.println(a);
    }//GEN-LAST:event_TxtFildePesquisarActionPerformed

    private void MenuPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuPesquisarActionPerformed

    private void MenuExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuExcluirActionPerformed

    private void MenuAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Movimentacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Movimentacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Movimentacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Movimentacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Movimentacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenus;
    private javax.swing.JPanel LabelAdicionarExcluir;
    private javax.swing.JLabel LabelDesconto;
    private javax.swing.JLabel LabelMovimentacoes;
    private javax.swing.JLabel LabelNomeCliente;
    private javax.swing.JLabel LabelValorTotal;
    private javax.swing.JButton MenuAdicionar;
    private javax.swing.JButton MenuAjuda;
    private javax.swing.JButton MenuExcluir;
    private javax.swing.JMenu MenuMovimentacoes;
    private javax.swing.JButton MenuPesquisar;
    private javax.swing.JMenu MenuProduto;
    private javax.swing.JPanel PanelAjudaPesquisa;
    private javax.swing.JMenu SubMenuCadastroCliente;
    private javax.swing.JMenuItem SubMenuCadastroProduto;
    private javax.swing.JMenuItem SubMenuConsultaCliente;
    private javax.swing.JMenuItem SubMenuConsutaCliente;
    private javax.swing.JTable TabelaMovimentacoes;
    private javax.swing.JTextField TxtFildePesquisar;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
