/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetointegrador;

/**
 *
 * @author pedrogomes
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Movimentacoes
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        PainelPrincipal = new javax.swing.JDesktopPane();
        BarraMenus = new javax.swing.JMenuBar();
        MenuMovimentacoes = new javax.swing.JMenu();
        MenuProduto = new javax.swing.JMenu();
        SubMenuCadastroProduto = new javax.swing.JMenuItem();
        SubMenuConsutaCliente = new javax.swing.JMenuItem();
        SubMenuCadastroCliente = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        SubMenuConsultaCliente = new javax.swing.JMenuItem();
        MenuRelatorios = new javax.swing.JMenu();
        MenuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movimentações");
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        PainelPrincipal.setBackground(java.awt.Color.blue);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                .addContainerGap())
        );

        BarraMenus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BarraMenus.setForeground(java.awt.Color.black);
        BarraMenus.setToolTipText("");
        BarraMenus.setDoubleBuffered(true);
        BarraMenus.setFocusable(false);
        BarraMenus.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        BarraMenus.setPreferredSize(new java.awt.Dimension(265, 30));
        BarraMenus.setVerifyInputWhenFocusTarget(false);

        MenuMovimentacoes.setBackground(java.awt.Color.black);
        MenuMovimentacoes.setForeground(java.awt.Color.black);
        MenuMovimentacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/cesta-de-compras-24.png"))); // NOI18N
        MenuMovimentacoes.setText("Movimentações");
        MenuMovimentacoes.setFont(MenuMovimentacoes.getFont().deriveFont(MenuMovimentacoes.getFont().getStyle() | java.awt.Font.BOLD));
        MenuMovimentacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMovimentacoesActionPerformed(evt);
            }
        });
        BarraMenus.add(MenuMovimentacoes);

        MenuProduto.setForeground(java.awt.Color.black);
        MenuProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/procurar-estoque-24.png"))); // NOI18N
        MenuProduto.setText("Produto");
        MenuProduto.setFont(MenuProduto.getFont().deriveFont(MenuProduto.getFont().getStyle() | java.awt.Font.BOLD));
        MenuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProdutoActionPerformed(evt);
            }
        });

        SubMenuCadastroProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/adicionar24.png"))); // NOI18N
        SubMenuCadastroProduto.setText("Cadastro");
        SubMenuCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuCadastroProdutoActionPerformed(evt);
            }
        });
        MenuProduto.add(SubMenuCadastroProduto);

        SubMenuConsutaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/pesquisa.png"))); // NOI18N
        SubMenuConsutaCliente.setText("Consulta");
        MenuProduto.add(SubMenuConsutaCliente);

        BarraMenus.add(MenuProduto);

        SubMenuCadastroCliente.setForeground(java.awt.Color.black);
        SubMenuCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/adicionar-usuário-masculino-24.png"))); // NOI18N
        SubMenuCadastroCliente.setText("Cliente");
        SubMenuCadastroCliente.setFont(SubMenuCadastroCliente.getFont().deriveFont(SubMenuCadastroCliente.getFont().getStyle() | java.awt.Font.BOLD));

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/adicionar-usuário-masculino-24.png"))); // NOI18N
        jMenuItem6.setText("Cadastro");
        SubMenuCadastroCliente.add(jMenuItem6);

        SubMenuConsultaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/procurar-usuário-masculino-24.png"))); // NOI18N
        SubMenuConsultaCliente.setText("Consulta");
        SubMenuCadastroCliente.add(SubMenuConsultaCliente);

        BarraMenus.add(SubMenuCadastroCliente);

        MenuRelatorios.setForeground(java.awt.Color.black);
        MenuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/graficoPizza.png"))); // NOI18N
        MenuRelatorios.setText("Relatórios");
        MenuRelatorios.setFont(MenuRelatorios.getFont().deriveFont(MenuRelatorios.getFont().getStyle() | java.awt.Font.BOLD));
        BarraMenus.add(MenuRelatorios);

        MenuSobre.setForeground(java.awt.Color.black);
        MenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetointegrador/img/sobre-24.png"))); // NOI18N
        MenuSobre.setText("Sobre");
        MenuSobre.setFont(MenuSobre.getFont().deriveFont(MenuSobre.getFont().getStyle() | java.awt.Font.BOLD));
        BarraMenus.add(MenuSobre);

        setJMenuBar(BarraMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SubMenuCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuCadastroProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubMenuCadastroProdutoActionPerformed

    private void MenuMovimentacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMovimentacoesActionPerformed
        MovimentacoesInternalFrame telaMovimentacoes = new MovimentacoesInternalFrame();
        PainelPrincipal.add(telaMovimentacoes);
        telaMovimentacoes.setVisible(true);
    }//GEN-LAST:event_MenuMovimentacoesActionPerformed

    private void MenuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProdutoActionPerformed
        MovimentacoesInternalFrame telaMovimentacoes = new MovimentacoesInternalFrame();
        PainelPrincipal.add(telaMovimentacoes);
        telaMovimentacoes.setVisible(true);    }//GEN-LAST:event_MenuProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenus;
    private javax.swing.JMenu MenuMovimentacoes;
    private javax.swing.JMenu MenuProduto;
    private javax.swing.JMenu MenuRelatorios;
    private javax.swing.JMenu MenuSobre;
    private javax.swing.JDesktopPane PainelPrincipal;
    private javax.swing.JMenu SubMenuCadastroCliente;
    private javax.swing.JMenuItem SubMenuCadastroProduto;
    private javax.swing.JMenuItem SubMenuConsultaCliente;
    private javax.swing.JMenuItem SubMenuConsutaCliente;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
